### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by lander2k2** [mbahvw/kit-katacoda-scenarios#1]
Overall, is great.  Just some nits that caught my eye while going through

## Multiple Steps
- When you have a sentence that introduces a command, sometimes you have a colon at the end of the sentence, sometimes not.  For consistency, suggest adding colons to all (or removing from all).
- The bullet indentation seems inconsistent.  In some places the bullet is nested when checking results, but not always.  I'm not sure nesting is really needed.

## Step 2
- The second command has an extra space before `config`: `kubectl  config get-contexts`

## Step 12
- There's a typo near the end: "nagigate"

## Step 13
- This sentence seems a bit disjointed:  "Now let's get again all the pods name along with their new nginx image version:"

## Step 14
- "Patching can be to partially" ==> "Patching can be used to partially"
- "...to create an nginx container application using the kubectl and with some label..." ==> "...to create an nginx container with a label using kubectl..."
- suggest explaining a little about the `--generator` flag on the run command

## Step 16
- First sentence seems to have title in it: "Additional Resources Thank you going through this scenario."

**Comment by mbahvw** [comment]
Thanks Rich! I will get this sorted out shortly. I appreciate the feedback!1

**Comment by mbahvw** [comment]
Issue has been resolved.
